### ISSUE TITLE
An Item with the same key has already been added

### ISSUE THREAD

**Issue by ramangupta44** [JeffDarchuk/EPExpressTab#6]
Hi guys,

After installing this module, following the documentation, we created two new tabs using the EpExpressViewModel base class. After doing all that, we are getting this error:
![EP-Error](https://user-images.githubusercontent.com/36916946/111308687-005e1100-8681-11eb-8c02-8541945f7ce6.png)

Has anyone any idea about that?

Thanks
Raman

**Comment by JeffDarchuk** [comment]
First disable the EPExpressTabs module then go into your core database and navigate to this item: {87EE30C3-115F-4AEB-8C9E-BB784912011C}

iterate over the children checking the `Placeholder Name` field.  I suspect you have a duplicate when it's required that they're unique. 

By default there are 4 tabs all with a `Placeholder Name` that matches their item name
![image](https://user-images.githubusercontent.com/12616331/111315884-07a10280-8620-11eb-9041-451916a783ab.png)

**Comment by ramangupta44** [comment]
Thanks, @JeffDarchuk. I was able to find and remove duplicate keys under {87EE30C3-115F-4AEB-8C9E-BB784912011C} in the core DB. Just wondering why keys are getting duplicated each time after deployment.

**Comment by JeffDarchuk** [comment]
If it's generating items on each deployment i'd check for multiple EPExpressTab registration objects in your binaries.  If they both have the same namespace in the solution then you may run into this problem.  Check to make sure you don't have multiple tabs defined in the same namespace.  Can you share what your `Placeholder Name` field was in the duplicated entry?
